movieproject/movieapp/urls.py
from django.urls import path, include

from movieapp import views
app_name = "movieapp"

urlpatterns = [


    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.detail,name="detail"),
     path('add/',views.add,name="add"),
     path('update/<int:movie_id>',views.update,name="update"),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.CharField(max_length=250)
    year=models.IntegerField()
    imag=models.ImageField(upload_to="gallery")

def __str__(self):
    return self.name

movieproject/movieapp/forms.py
from django import forms

from movieapp.models import Movies


class modelform(forms.ModelForm):
    class Meta:
        model=Movies
        fields=["name","desc","year","imag"]

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from movieapp.forms import modelform
from movieapp.models import Movies


def index(request):
    obj1=Movies.objects.all()
    context={"key1":obj1}
    print(type(obj1))
    print(obj1)
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return render(request,"detail.html",{"key2":movie})
def add(request):
    if request.method=="POST":
        name=request.POST.get("name")
        desc=request.POST.get("desc")
        year=request.POST.get("year")
        imag=request.FILES.get("imag")
        movie=Movies(name=name,desc=desc,year=year,imag=imag)
        movie.save()
    return render(request,"add.html")
def update(request,movie_id):
    movobj=Movies.objects.get(id=movie_id)
    form1=modelform(request.POST or None,request.FILES,instance=movobj)
    if form1.is_valid():
        form1.save()
        return redirect ("/")
    return render(request,"update.html",{"key1":movobj,"key2":form1})

movieproject/templates/add.html
{% extends "base.html" %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="desc" placeholder="enter description">
    <input type="text" name="year" placeholder="enter year">
    <input type="FILE" name="imag" placeholder="upload image">

    <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
{{ '<' }}{{ '!DOCTYPE html>' }}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">

    Online moviestore
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/detail.html
{% extends "base.html" %}
{% block body %}
<img src="{{key2.imag.url}}" width="100" height="100"><br>
{{key2.name}}<br>
{{key2.desc}}<br>
{{key2.year}}
<a class="btn btn-warning"  href="{% url 'movieapp:update' key2.id %}">update
{% endblock %}

movieproject/templates/detail1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{key2.name}}
{{key2.desc}}
{{key2.year}}
</body>
</html>

movieproject/templates/index.html
{% extends "base.html" %}
{% block body %}

{% for i in key1 %}


<img src="{{i.imag.url}}" width="100" height="100">


<a href="{% url 'movieapp:detail' i.id %}" > {{i.name}}<br>

{% endfor %}
{% endblock %}

movieproject/templates/index1.html
{% load static %}
{{ '<' }}{{ '!DOCTYPE html>' }}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "style.css" %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">

    Online moviestore
  </a>
</nav>
<h1> this is a index file</h1>
{% for i in key1 %}

<a href ="movie/{{i.id}}/"> {{i.name}}
    <a href ="{% url 'movieapp:detail' i.id %}">{{i.name}}
{% endfor %}
</body>
</html>

movieproject/templates/update.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{key2.as_p}}
    <input type="submit">
</form>